[project]
name = "stafit-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "tabulate>=0.9.0",
]

[dependency-groups]
dev = [
    "black>=26.1.0",
    "pytest>=8.0.0",
    "pytest-cov>=7.0.0",
]
